services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - "4000:4000"
    env_file:
      - backend/.env
    environment:
      - NODE_ENV=development
    depends_on:
      - db

  db:
    image: postgres:13
    env_file:
      - backend/.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      # - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - backend/.env
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  pgdata:
