services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - "4000:4000"
    env_file:
      - backend/.env
    environment:
      - NODE_ENV=development
