name: Node.js CI Frontend

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.18.0]

    env:
        NEXT_WEBSITE_URL: ${{ secrets.NEXT_WEBSITE_URL }}

    steps:
    - uses: actions/checkout@v4

        # Navigate to the frontend directory before running npm commands
    - name: Change Directory to Frontend
      working-directory: /home/janitha/actions-runner/_work/wedding-directory/wedding-directory/frontend

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Navigate to the frontend directory before running npm commands
    - name: Change Directory to Frontend
      working-directory: /home/janitha/actions-runner/_work/wedding-directory/wedding-directory/frontend
      run: pwd

    - name: Install dependencies
      run: npm ci
      working-directory: /home/janitha/actions-runner/_work/wedding-directory/wedding-directory/frontend

    - name: Build the frontend
      run: npm run build --if-present
      working-directory: /home/janitha/actions-runner/_work/wedding-directory/wedding-directory/frontend

    - name: Restart the application using PM2
      run: pm2 restart 0
      working-directory: /home/janitha/actions-runner/_work/wedding-directory/wedding-directory/frontend
