name: Node.js CI Frontend

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.18.0]
    env:
        NEXT_WEBSITE_URL: ${{ secrets.NEXT_WEBSITE_URL }}
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Change Directory
      run: cd /home/janitha/actions-runner/_work/wedding-directory/wedding-directory/frontend
    - run: npm ci
    - run: npm run build --if-present
    - name: Change Directory
      run: cd /home/janitha/actions-runner/_work/wedding-directory/wedding-directory/frontend
    - run: pm2 restart 0
