name: Frontend CI/CD
on:
  push:
    paths:
     - 'frontend/**'
    branches: [ "main" ]

jobs:
  build:
    name: Build Frontend
    runs-on: self-hosted
    defaults:
     run:
      working-directory: './frontend'

    strategy:
      matrix:
        node-version: [20.18.0]

    env:
      NEXT_WEBSITE_URL: ${{ secrets.NEXT_WEBSITE_URL }}

    steps:
    - uses: actions/checkout@v4

    # Set up Node.js
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
          filters: |
            frontend:
              - 'frontend/**' 
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

    # Install dependencies in the frontend folder
    - name: Install dependencies
      run: npm ci
      working-directory: './frontend'

    # Build the frontend
    - name: Build the frontend
      run: npm run build --if-present
      working-directory: './frontend'

    # Restart the application using PM2
    - name: Restart the application
      run: pm2 restart 0
      working-directory: './frontend'
